[short_url]
    addr = "mysql_me:3306"
    user = "root"
    pwd = "123456"
    dbname = "dev"
    table_cnt = 1

[redis]
    addr = "redis_me:6379"
    pwd = ""

[logger]
    file_path = "./logs/app.log"
    level = 1

[server]
    machine_id = 1
    domain = "http://39.100.89.154"
