version: '3'
services:
  mysql:
    image: docker.io/mysql:5.7.20
    container_name: mysql_me
    build: ./mysql
    volumes:
      - /root/golang/gopath/src/github.com/daysleep666/short_chain/data/mysql/data:/var/lib/mysql
      #- /root/golang/gopath/src/github.com/daysleep666/short_chain/builder/mysql/conf:/etc/mysql/conf.d/
      - /root/golang/gopath/src/github.com/daysleep666/short_chain/builder/mysql/init:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    networks:
      - default
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  redis:
    image: docker.io/redis:5.0
    container_name: redis_me
    build: ./redis
    networks:
      - default
    volumes:
      - /root/golang/gopath/src/github.com/daysleep666/short_chain/data/redis/data:/data
    ports:
      - "6379:6379"

  nginx:
    image: docker.io/nginx:latest
    container_name: nginx_me
    build: ./nginx
    volumes:     
     - /root/golang/gopath/src/github.com/daysleep666/short_chain/builder/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
     - /root/golang/gopath/src/github.com/daysleep666/short_chain/builder/nginx/conf.d/config:/etc/nginx/conf.d/config
    networks:
      - default
    depends_on:
     - shortchain
    ports:
     - "80:80"

  shortchain:
    image: shortchain:0.2
    container_name: shortchain
    build: ./
    networks:
      - default
    volumes:
     - /root/golang/gopath/src/github.com/daysleep666/short_chain/data/logs:/dist/logs
    depends_on:
     - mysql
     - redis
    ports:
     - "1234:1234"
     - "8080:8080"
    restart: always
